name: Build Extensions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions to allow the workflow to push changes
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, mbstring, dom
          coverage: none
      
      - name: Validate composer.json
        run: composer validate
      
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Build extensions
        run: php scripts/build.php all
      
      - name: List build directory
        run: ls -la build/
      
      - name: Upload artifacts (for workflow record)
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: build/*.gluex
          if-no-files-found: warn
          retention-days: 7
          
      # New steps to commit the built extensions back to the repository
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push if changes
        run: |
          # Check if there are any changes to commit
          if [[ -n $(git status --porcelain build/) ]]; then
            git add build/
            git commit -m "Update built extensions [skip ci]"
            
            # For pull requests
            if [[ -n "${{ github.head_ref }}" ]]; then
              git push origin HEAD:${{ github.head_ref }}
            # For direct pushes to branches
            else
              git push origin HEAD:${{ github.ref_name }}
            fi
            
            echo "✅ Successfully committed updated extension packages to the repository"
          else
            echo "ℹ️ No changes to commit"
          fi